package top.javinjunfeng.model.entity;

import lombok.Data;

import java.util.Date;
//@Data
public class DbInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.id
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.db_code
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private String dbCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.db_type
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private String dbType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.db_ip
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private String dbIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.db_port
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private String dbPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.db_name
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.db_username
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private String dbUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.db_password
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private String dbPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_info.create_time
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.id
     *
     * @return the value of db_info.id
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.id
     *
     * @param id the value for db_info.id
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.db_code
     *
     * @return the value of db_info.db_code
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public String getDbCode() {
        return dbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.db_code
     *
     * @param dbCode the value for db_info.db_code
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setDbCode(String dbCode) {
        this.dbCode = dbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.db_type
     *
     * @return the value of db_info.db_type
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public String getDbType() {
        return dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.db_type
     *
     * @param dbType the value for db_info.db_type
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setDbType(String dbType) {
        this.dbType = dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.db_ip
     *
     * @return the value of db_info.db_ip
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public String getDbIp() {
        return dbIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.db_ip
     *
     * @param dbIp the value for db_info.db_ip
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setDbIp(String dbIp) {
        this.dbIp = dbIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.db_port
     *
     * @return the value of db_info.db_port
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public String getDbPort() {
        return dbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.db_port
     *
     * @param dbPort the value for db_info.db_port
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setDbPort(String dbPort) {
        this.dbPort = dbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.db_name
     *
     * @return the value of db_info.db_name
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.db_name
     *
     * @param dbName the value for db_info.db_name
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.db_username
     *
     * @return the value of db_info.db_username
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public String getDbUsername() {
        return dbUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.db_username
     *
     * @param dbUsername the value for db_info.db_username
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setDbUsername(String dbUsername) {
        this.dbUsername = dbUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.db_password
     *
     * @return the value of db_info.db_password
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public String getDbPassword() {
        return dbPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.db_password
     *
     * @param dbPassword the value for db_info.db_password
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setDbPassword(String dbPassword) {
        this.dbPassword = dbPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_info.create_time
     *
     * @return the value of db_info.create_time
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_info.create_time
     *
     * @param createTime the value for db_info.create_time
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}