package top.javinjunfeng.model.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import top.javinjunfeng.model.entity.DbInfoDO;
@Mapper
public interface DbInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    int insert(DbInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    int insertSelective(DbInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    DbInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    int updateByPrimaryKeySelective(DbInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_info
     *
     * @mbg.generated Mon Mar 18 17:49:20 CST 2019
     */
    int updateByPrimaryKey(DbInfoDO record);

    DbInfoDO selectByDbCode(@Param("dbCode") String dbCode);

}